version: '3'

volumes:
  postgres_volume:

services:
  weather-db:
    image: postgres:14.0
    env_file:
      - ./deploy/env/.env.local
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "${PG_PORT}:${PG_PORT}"
    command: -p ${PG_PORT}